### ISSUE TITLE
关于ThermalGAN

### ISSUE THREAD

**Issue by keruoya** [fangyuanmao/PID#10]
感谢您非常棒的工作 ！ 我想尝试复现您的结果 ， 看到您将ThermalGAN作为对比，但是ThermalGAN的实施的readme不详细 ， 作者也没给出解释 ， 可以请问您ThermalGAN 和 其他网络的实施细节吗

**Comment by fangyuanmao** [comment]
你好，我们都是按照现有工作的开源代码进行复现。如果有关于网络的实施细节问题，咨询原作者应该会更准确。
