### ISSUE TITLE
使用其他数据集finetune

### ISSUE THREAD

**Issue by jeromefan** [fangyuanmao/PID#11]
感谢您非常棒的工作 ！ 我想尝试使用LLVIP来finetune您所提供的kaist的预训练模型以观察是否能有效提升该模型在llvip数据集上的表现（因为目前的预训练模型在kaist上表现良好，但更换数据集后表现不尽人意）。

我也注意到您ldm文件夹下是有llvip数据集的相关文件的。

您是否可以指导一下我要通过哪些命令以及修改哪些地方的值能够顺利finetune吗

**Comment by fangyuanmao** [comment]
谢谢您对我们工作的关注与认可。我们针对自动驾驶场景做了充分的测试，但并未在LLVIP数据集上进行训练测试。建议可以参照训练PID的流程，尝试先使用训练集的红外图片预训练TeVNet，再将该TeVNet嵌入到模型中（修改config中的TeVNet checkpoint load path），可能会提升效果。

**Comment by WheatCao** [comment]
请问楼主在llvip上的测试成功了吗？指标和效果如何呢？
