### ISSUE TITLE
请问如何进行指标的测量

### ISSUE THREAD

**Issue by keruoya** [fangyuanmao/PID#13]
非常抱歉打扰您 我在您的代码中没有找到关于直指标测量的代码 我用您在kaist数据集上的公开的预训练权重对set00v0000场景的1000张可见光图片进行测试 用pyiqa库的ssim,psnr,fid进行测量并求和取均值 发现指标比您论文的指标还要高很多 请问是不是我测量的方法有问题？或者是因为数据集没有清洗 单一重复的场景太多 ？可以请问您测试的具体细节吗，我测量的指标如下：
![image](https://github.com/user-attachments/assets/c628268c-140d-41df-9a1d-5fe5ae892664)

**Comment by fangyuanmao** [comment]
您好，我们的实验是遵循了KAIST原始的训练集与测试集的划分。具体来说我们的训练集是set00-05，测试集是set06-11，具体的测试文件图片名称见附件。
[test-all-20.txt](https://github.com/user-attachments/files/17733082/test-all-20.txt)
[train-all-04.txt](https://github.com/user-attachments/files/17733084/train-all-04.txt)
