### ISSUE TITLE
配置环境时的一些问题

### ISSUE THREAD

**Issue by NicoAndSteven** [fangyuanmao/PID#17]
在使用您的这条指令时conda env create --file=environment.yaml我遇到了一些错误，具体在于提示项目中没有setup.py文件，尝试删掉配置文件最后三行的-e后下载您发布的训练后的模型也无法使用，能否请您详尽讲一下使用方法，感激不尽
![image](https://github.com/user-attachments/assets/1f8dcd9b-58ff-4b39-880d-169668bdc481)

**Comment by fangyuanmao** [comment]
您好，您叙述中所提到的问题，可能是版本不兼容所导致的，建议更换合适版本。另外，我们更新了环境的yaml文件，希望能更正这个问题。
