### ISSUE TITLE
How is preprocessing done to align data in FLIR?

### ISSUE THREAD

**Issue by JayParanjape** [fangyuanmao/PID#18]
From the data link provided, I was able to download the FLIR-ADAS dataset. However, the visible and thermal videos in the training and validation folders don't belong to the same scene (i.e. they are not paired). How was this handled ?

Thanks

**Comment by fangyuanmao** [comment]
To keep same dataset with SOTA work, we use the FLIRv1 dataset, which can be found in data-link. FLIRv1 has an almost paired dataset, but still remains some mismatching. We have already uploaded the data alignment code for FLIRv1 dataset.

**Comment by JayParanjape** [comment]
The data link leads to the v2 dataset probably. The files that I downloaded look like this: video-7cJxWPFMvPdSiWASY-frame-000000-zCbGu9ErmZn6AHfEB.jpg
Could you guide me to the correct dataset if this is not the one?

Thanks
Jay

**Comment by fangyuanmao** [comment]
<img width="1125" alt="截屏2024-12-31 11 55 41" src="https://github.com/user-attachments/assets/73132f58-69c4-4c5c-8b4c-302eb42256d3" />
FLIRv1 is available at the web. And there is also a version of aligned dataset provided by others https://github.com/zonaqiu/FLIR-align

**Comment by JayParanjape** [comment]
I see. Thanks
