### ISSUE TITLE
About GPU and training time

### ISSUE THREAD

**Issue by chaunceywx** [fangyuanmao/PID#2]
I want to ask what platform do you used to train your models?   8*A100?
And how long to train this model completely with KAIST or FLIR?

**Comment by fangyuanmao** [comment]
Thanks for your question. We use 4*V100, with a batchsize=48, accumulate grad=2. The whole training time of model completely on KAIST is 110 hours without testing and 120 hours on FLIR.

**Comment by Zhangjunyin** [comment]
Yes, I ran into the same problem. When I run script "PID-FLIR-c=E.yaml" with k1 = 50, k2 = 50, and batch size = 2, the GPU memory usage reaches about 40 GB. To keep the batch size used in the original paper, I increased accumulate_grad_batches, i.e., 48 = 4 (GPUs) × 2 (batch size) × 6 (accumulate_grad_batches).
