### ISSUE TITLE
Pretrained Model Download Issue on OneDrive

### ISSUE THREAD

**Issue by yhhxt** [fangyuanmao/PID#3]
I was attempting to download the pretrained weights you provided, specifically the links for PID_KAIST.zip and PID_FLIR.zip, but it seems that the links are no longer working. Could you please update them?

**Comment by yhhxt** [comment]
The links are now working, and I can download them successfully. Thanks.

**Comment by liutian123** [comment]
I can't open the download link for OneDrive now. Can you please update them?

**Comment by fangyuanmao** [comment]
> I can't open the download link for OneDrive now. Can you please update them?

Please check your network. Thanks.
