### ISSUE TITLE
RGB<->LWIR image alignment needed for training

### ISSUE THREAD

**Issue by yonidishon** [fangyuanmao/PID#4]
In section 4.3 of the paper you wrote: "we conduct preprocessing to align the data"
Could you specify or give a code example of what alignment did you do exactly?

**Comment by fangyuanmao** [comment]
Thanks for your question. We find that image bias between different modality in FLIR is related to the image size. Thus, we align the images RGB and IR in a simple way, which is based on their image size. Part of alignment code is shown below.

```
        if h_visi == 1024 and w_visi == 1280: 
            img_ir = img_ir[32:32+int(520*512/640), 70:70+int(520),:]
        elif h_visi == 1600 and w_visi == 1800:
            hb = int((h_visi - s * h_ir ) //2) - 20
            wb = int((w_visi - s * w_ir ) //2) + 50
            img_visible = img_visible[hb:hb+int(s*h_ir), wb:wb+int(s*w_ir), :]
        elif h_visi == 480 and w_visi == 720:
            hb = 45
            wb = 138
            width = 480
            img_visible = img_visible[hb:hb+int(width*512/640),wb:wb+int(width),:]
        elif h_visi == 1536 and w_visi == 2048:
            hb = 35
            wb = 65
            width = 480
            img_ir = img_ir[hb:hb+int(width*512/640),wb:wb+int(width),:]


```
We will release the data preprocessing code soon.

**Comment by yonidishon** [comment]
Thank you very much for paper and released implementation! 
Tnx also for the quick reply.
I'm closing the issue.

**Comment by yonidishon** [comment]
Just one more question/comment
So in your pre-processing you didn't handle:
1. Distortion 
2. Focal length (scale) changes
And only handled shift?
Also in the code above you gave what is the variable "s" value?

**Comment by fangyuanmao** [comment]
Thanks for your question. 
We have modified the code above to it more clear.
In FLIR dataset pre-processing, we find that too many pre-processing may be harmful to the quality of original images, thus we only handle the shift bias to keep the quality. For fair comparison, we compare all the methods in a same pre-processing dataset.
If you have any better data pre-processing methods, please let us know. THANKS!

> Thanks for your question. We find that image bias between different modality in FLIR is related to the image size. Thus, we align the images RGB and IR in a simple way, which is based on their image size. Part of alignment code is shown below.
> 
> ```
> h_visi, w_visi, _ = img_visible.shape
> h_ir, w_ir, _ = img_ir.shape
> 
> if h_visi == 1024 and w_visi == 1280: 
>     img_ir = img_ir[32:448, 70:590, :]
> elif h_visi == 480 and w_visi == 720:
>     img_visible = img_visible[45:429, 138:618, :]
> elif h_visi == 1536 and w_visi == 2048:
>     img_ir = img_ir[35:419, 65:545, :]
> elif h_visi == 1600 and w_visi == 1800:
>     hb = (h_visi - 2.5 * h_ir ) // 2 - 20
>     wb = (w_visi - 2.5 * w_ir ) // 2 + 50
>     img_visible = img_visible[hb:hb+int(2.5*h_ir), wb:wb+int(2.5*w_ir), :]
> else:
>   pass
> ```
> 
> We will release the data preprocessing code soon.
