### ISSUE TITLE
About model checkpoint

### ISSUE THREAD

**Issue by kay-kuo** [fangyuanmao/PID#5]
Hi, thanks for your great work.

When I load the checkpoint of KAIST, it reports `Recovering from ./PID_KAIST/epoch=000235-step=000059999.ckpt with 299 missing and 1048 unexpected keys`. Is this right? Thanks.

**Comment by fangyuanmao** [comment]
Thanks for your question. 
Please check if you have placed the `VQVAE-f8` checkpoint and `TeVNet` checkpoint in right paths which are set in `configs/latent-diffusion/kaist512-vqf8.yaml`. 
There may be some unexpected keys in VQVAE-f8 pretrained model(it doesn't matter), but others have no anomaly.

**Comment by kay-kuo** [comment]
Thanks. Yeah, there is something wrong with the path of ckpts.

**Comment by kay-kuo** [comment]
Thanks. Yeah, there is something wrong with the path of ckpts.
