### ISSUE TITLE
test model PID checkpoint for FLIR, k1=k2=50

### ISSUE THREAD

**Issue by mzalaki00** [fangyuanmao/PID#8]
Hi
thanks for your work.
can you clearly explain how to use PID checkpoint( for FLIR) for inference with rgb images??
your test script, yaml files belongs to tevnet, kaist and ... ! 
does it make any difference?

**Comment by fangyuanmao** [comment]
Thanks for your question. We only release the evaluation script for KAIST dataset. You can evaluate the result of KAIST dataset with our introduction. We will release the complete code as soon as the paper is accepted.

**Comment by mzalaki00** [comment]
sorry but I don't get it, is evaluation script just for KAIST dataset!? why? 
you mean if i use this model for predicting other dataset, it give wrong output. am i correct?

**Comment by fangyuanmao** [comment]
> Thanks for your question. We only release the evaluation script for KAIST dataset. You can evaluate the result of KAIST dataset with our introduction. We will release the complete code as soon as the paper is accepted.

1、"**release** the evaluation script for KAIST dataset"
2、The architecture of PID is the same one. But checkpoint differs among datasets. We will release the complete version after the paper is accepted.
